#
# Copyright 2010-2014 Fabric Software Inc. All rights reserved.
#

export SIXENSE_INCLUDE_DIR=$FABRIC_SCENE_GRAPH_DIR/ThirdParty/include/sixense
export SIXENSE_LIBRARY_DIR=$FABRIC_SCENE_GRAPH_DIR/ThirdParty/PreBuilt/$FABRIC_BUILD_OS/$FABRIC_BUILD_ARCH/$FABRIC_BUILD_TYPE/lib/sixense
export BOOST_INCLUDE_DIR=$FABRIC_SCENE_GRAPH_DIR/ThirdParty/Prebuilt/$FABRIC_BUILD_DIST/$FABRIC_BUILD_ARCH/Release/boost/1.55.0
export BOOST_LIBRARY_DIR=$FABRIC_SCENE_GRAPH_DIR/ThirdParty/Prebuilt/$FABRIC_BUILD_DIST/$FABRIC_BUILD_ARCH/Release/boost/1.55.0/lib
export FABRIC_EXTS_INSTALL_DIR=$FABRIC_DIR/Exts/BuiltinNoInstaller